name: Audit

on: push

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.4

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run:  |
        go build -v ./...

    - name: Run go vet
      run: go vet ./...

    - name: Run go test
      run: go test ./...
